package com.tracky.app.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Food Entry Entity
 * 
 * Represents a logged food entry (meal/snack).
 * Contains summary totals; individual items are in FoodItemEntity.
 */
@Entity(
    tableName = "food_entries",
    indices = [
        Index(value = ["date"]),
        Index(value = ["createdAt"])
    ]
)
data class FoodEntryEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    
    /**
     * Date of entry (ISO date: "YYYY-MM-DD")
     */
    val date: String,
    
    /**
     * Time of entry (ISO time: "HH:mm:ss")
     */
    val time: String,
    
    /**
     * Timestamp (epoch millis) for sorting
     */
    val timestamp: Long,
    
    /**
     * Total calories for all items in this entry
     */
    val totalCalories: Int,
    
    /**
     * Total carbs in grams
     */
    val totalCarbsG: Float,
    
    /**
     * Total protein in grams
     */
    val totalProteinG: Float,
    
    /**
     * Total fat in grams
     */
    val totalFatG: Float,
    
    /**
     * Analysis narrative generated by Gemini
     */
    val analysisNarrative: String?,
    
    /**
     * Path to locally stored photo (if any)
     */
    val photoPath: String?,
    
    /**
     * User's original input text
     */
    val originalInput: String?,
    
    /**
     * Entry creation timestamp (epoch millis)
     */
    val createdAt: Long,
    
    /**
     * Entry last update timestamp (epoch millis)
     */
    val updatedAt: Long
)

/**
 * Food Item Entity
 * 
 * Individual food item within a food entry.
 * Stores provenance and detailed nutrition data.
 */
@Entity(
    tableName = "food_items",
    indices = [
        Index(value = ["foodEntryId"])
    ]
)
data class FoodItemEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    
    /**
     * Foreign key to FoodEntryEntity
     */
    val foodEntryId: Long,
    
    /**
     * Name of the food item
     */
    val name: String,
    
    /**
     * Matched name from dataset/USDA (may differ from user input)
     */
    val matchedName: String?,
    
    /**
     * Quantity value
     */
    val quantity: Float,
    
    /**
     * Unit of measurement (g, oz, cup, piece, etc.)
     */
    val unit: String,
    
    /**
     * Calories for this item
     */
    val calories: Int,
    
    /**
     * Carbs in grams
     */
    val carbsG: Float,
    
    /**
     * Protein in grams
     */
    val proteinG: Float,
    
    /**
     * Fat in grams
     */
    val fatG: Float,
    
    /**
     * Provenance source: "dataset", "usda_fdc", "user_override"
     */
    val source: String,
    
    /**
     * Matched label/ID from source
     */
    val sourceId: String?,
    
    /**
     * Confidence score (0.0 - 1.0)
     */
    val confidence: Float,
    
    /**
     * Order within the entry for display
     */
    val displayOrder: Int
)
